# Generated by Django 5.2 on 2025-04-08 21:40

import candidatura.models
import candidatura.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('uf', models.CharField(choices=[('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('SP', 'São Paulo')], max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('EMI', 'Ensino Médio Incompleto'), ('EMC', 'Ensino Médio Completo'), ('ESI', 'Ensino Superior Incompleto'), ('ESC', 'Ensino Superior Completo')], max_length=3, null=True)),
                ('sobre_voce', models.CharField(max_length=300, verbose_name='Fale sobre você')),
                ('curriculo', models.FileField(blank=True, null=True, upload_to=candidatura.models.upload_curriculo, validators=[candidatura.validators.validate_pdf, candidatura.validators.validate_file_size], verbose_name='Currículo (PDF até 5MB)')),
                ('aceita_lgpd', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
