# Generated by Django 5.2 on 2025-04-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criterios', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_planejada_inicio', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NAO_SELECIONADO', 'Não selecionado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONTRATADO', 'Contratado'), ('NAO_APTO', 'Não apto no momento')], default='EM_ANDAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidatura.candidatura')),
                ('vaga', models.ForeignKey(blank=True, default='Nenhuma', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vagas.vaga')),
            ],
        ),
    ]
